protected/controllers/AdminController.php
<?php

class AdminController extends Controller
{
  /**
   * Declares class-based actions.
   */
  public function actions()
  {

    return array(
      // captcha action renders the CAPTCHA image displayed on the contact page
      'captcha'=>array(
        'class'=>'CCaptchaAction',
        'backColor'=>0xFFFFFF,
      ),
      // page action renders "static" pages stored under 'protected/views/site/pages'
      // They can be accessed via: index.php?r=site/page&view=FileName
      'page'=>array(
        'class'=>'CViewAction',
      ),
    );
  }

  /**
   * This is the default 'index' action that is invoked
   * when an action is not explicitly requested by users.
   */
  public function actionIndex()
  {
    // renders the view file 'protected/views/site/index.php'
    // using the default layout 'protected/views/layouts/main.php'
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
      $this->redirect(array('admin/post'));
    }
  }

  /**
   * This is the action to handle external exceptions.
   */
  public function actionError()
  {
    if($error=Yii::app()->errorHandler->error)
    {
      if(Yii::app()->request->isAjaxRequest)
        echo $error['message'];
      else
        $this->render('error', $error);
    }
    $this->layout = 'adminmain';
  }

  /**
   * Displays the login page
   */
  public function actionLogin()
  {
    $model=new LoginForm;

    // if it is ajax validation request
    if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
    {
      echo CActiveForm::validate($model);
      Yii::app()->end();
    }

    // collect user input data
    if(isset($_POST['LoginForm']))
    {
      $model->attributes=$_POST['LoginForm'];
      // validate user input and redirect to the previous page if valid
      if($model->validate() && $model->login())
        $this->redirect(array('admin/index'));
    }
    // display the login form
    $this->layout = 'adminmain';
    $this->render('login',array('model'=>$model));
  }

  /**
   * Logs out the current user and redirect to homepage.
   */
  public function actionLogout()
  {
    Yii::app()->user->logout();
    $this->layout = 'adminmain';
    $this->redirect(array('admin/login'));
  }

  public function actionArticle(){

    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
      $model = new Article;

      if (isset($_POST['Article'])) {
        $model->attributes = $_POST['Article'];
        $model->created_at = date('Y-m-d H:i:s');
        if($model->save()){
          $this->redirect(array('admin/post'));
        }else{
          $this->render('article',array('model'=>$model));
        }
        }else{
          $this->render('article',array('model'=>$model));
        }
      }
    }

  public function actionPost()
  {
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
      $data = Article::model()->findAll(array('order' => 'created_at DESC'));
      $this->render('post', array('data' => $data));
    }
  }

  public function actionEditarticle($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Article::model()->findBySql('SELECT * FROM article WHERE id = "' . $id . '"');

    if (isset($_POST['Article'])) {
      $data->attributes = $_POST['Article'];
      $data->created_at = date('Y-m-d H:i:s');
      if($data->save()){
        $this->redirect(array('admin/post'));
      }else{
        $this->render('editarticle', array('data' => $data));
      }
      }else{
        $this->render('editarticle', array('data' => $data));
      }
    }
  }

  public function actionDeletearticle($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Article::model()->findBySql('SELECT * FROM article WHERE id = "' . $id . '"');

      if($data->delete()){
        $this->redirect(array('admin/post'));
      }else{
        $this->redirect(array('admin/post'));
      }
    }
  }

  public function actionShowarticle($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Article::model()->findBySql('SELECT * FROM article WHERE id = "' . $id . '"');

      if($data->delete()){
        $this->redirect(array('admin/detailarticle'));
      }else{
        $this->redirect(array('admin/detailarticle'));
      }
    }
  }

  public function actionQuestions(){
    $this->layout = 'adminmain';
    $data = Question::model()->findAll(array('order' => 'schedule DESC'));
    $this->render('questions', array('data' => $data));
  }

  public function actionNewquest(){
    $this->layout = 'adminmain';
    $model = new Question;
    $choice = array();

    if (isset($_POST['Question'])) {
      $model->attributes = $_POST['Question'];
      for($i=0; $i<count($_POST['Question']['multiple_choice']); $i++){
        $ask = $i+1;
        $sem = $ask>=3 ? "" : ";";
        array_push($choice, $ask."==".$_POST['Question']['multiple_choice'][$i].$sem);
      }
      $model->multiple_choice = implode('',$choice);
      $model->schedule = date('Y-m-d H:i:s');
      if($model->save()){
        $this->redirect(array('admin/questions'));
      }else{
        $this->render('newquest',array('model'=>$model));
      }
    }else{
      $this->render('newquest',array('model'=>$model));
    }
  }

  public function actionEditquest($id){
    $this->layout = 'adminmain';
    $model = Question::model()->findBySql('SELECT * FROM question WHERE id = "' . $id . '"');
    $choice = array();

    if (isset($_POST['Question'])) {
      $model->attributes = $_POST['Question'];
      for($i=0; $i<count($_POST['Question']['multiple_choice']); $i++){
        $ask = $i+1;
        $sem = $ask>=3 ? "" : ";";
        array_push($choice, $ask."==".$_POST['Question']['multiple_choice'][$i].$sem);
      }
      $model->multiple_choice = implode('',$choice);
      $model->schedule = date('Y-m-d H:i:s');
      if($model->save()){
        $this->redirect(array('admin/questions'));
      }else{
        $this->render('editquest',array('model'=>$model));
      }
    }else{
      $this->render('editquest',array('model'=>$model));
    }
  }

  public function actionDeletequest($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Question::model()->findBySql('SELECT * FROM question WHERE id = "' . $id . '"');

      if($data->delete()){
        $this->redirect(array('admin/questions'));
      }else{
        $this->redirect(array('admin/questions'));
      }
    }
  }
}

protected/views/admin/article.php
<div class="home">
  <div class="register">
    <div class="content bodyText">
      <?php
        $form = $this->beginWidget('CActiveForm', array(
          'id' => 'user-form',
          'enableAjaxValidation' => false,
        ));
      ?>
      <?php echo $form->labelEx($model, 'Nama Article'); ?><br />
      <?php echo $form->textField($model, 'text'); ?>
      <?php echo $form->error($model, 'text'); ?>
      <br /><br />
      <?php
        $this->widget('application.extensions.cleditor.ECLEditor',
          array(
            'model'=>$model,
            'attribute'=>'isi_article',
            'options'=>array('width'=>'600', 'height'=>250, 'useCSS'=>true,),
            'value'=>$model->isi_article,
        ));
      ?>
      <br /><br />
      <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
      <?php $this->endWidget(); ?>
    </div>
  </div>
</div>

protected/views/admin/contact.php
<?php
$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

protected/views/admin/editarticle.php
<div class="home">
  <div class="register">
    <div class="content bodyText">
      <?php
        $form = $this->beginWidget('CActiveForm', array(
          'id' => 'article-form',
          'enableAjaxValidation' => false,
        ));
      ?>
      <?php echo $form->labelEx($data, 'Nama Article'); ?><br />
      <?php echo $form->textField($data, 'text'); ?>
      <?php echo $form->error($data, 'text'); ?>
      <br /><br />
      <?php
        $this->widget('application.extensions.cleditor.ECLEditor', array(
          'model'=>$data,
          'attribute'=>'isi_article', //Model attribute name. Nome do atributo do modelo.
          'options'=>array(
              'width'=>'600',
              'height'=>250,
              'useCSS'=>true,
          ),
          'value'=>$data->isi_article, //If you want pass a value for the widget. I think you will. Se você precisar passar um valor para o gadget. Eu acho irá.
      ));
      ?>
      <br /><br />
      <?php echo CHtml::submitButton($data->isNewRecord ? 'Create' : 'Save'); ?>
      <?php $this->endWidget(); ?>
    </div>
  </div>
</div>

protected/views/admin/editquest.php
<div class="home">
  <div class="register">
    <div class="content bodyText">
      <?php
        $form = $this->beginWidget('CActiveForm', array(
          'id' => 'user-form',
          'enableAjaxValidation' => false,
          'enableClientValidation' => true,
          'clientOptions' => array(
              'validateOnSubmit' => true,
          ),
        ));
        $choices = explode(";", $model->multiple_choice);
      ?>
      <?php echo $form->labelEx($model, 'pertanyaan'); ?><br />
      <?php echo $form->textArea($model, 'text',array('size'=>90)); ?>
      <?php echo $form->error($model, 'text'); ?>
      <br /><br />
      <?php echo $form->labelEx($model, 'insert_choice'); ?><br />
      1.
      <?php echo $form->textField($model, 'multiple_choice[0]', array('value' => str_replace("1==", '', $choices[0]), 'required' => true)); ?>
      <br /><br />
      2.
      <?php echo $form->textField($model, 'multiple_choice[1]', array('value' => str_replace("2==", '', $choices[1]),'required' => true)); ?>
      <br /><br />
      3.
      <?php echo $form->textField($model, 'multiple_choice[2]', array('value' => str_replace("3==", '', $choices[2]),'required' => true)); ?>
      <br /><br />
      <?php echo $form->labelEx($model, 'the_aswer_is'); ?><br />
      <?php echo $form->textField($model, 'answer'); ?>
      <br /><br />
      <?php echo $form->labelEx($model, 'hint'); ?><br />
      <?php echo $form->textArea($model, 'hint'); ?>
      <br /><br />
      <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
      <?php $this->endWidget(); ?>
    </div>
  </div>
</div>

protected/views/admin/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/admin/index.php
<?php $this->pageTitle=Yii::app()->name; ?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

<p>Congratulations! You have successfully created your Yii application.</p>

<p>You may change the content of this page by modifying the following two files:</p>
<ul>
	<li>View file: <tt><?php echo __FILE__; ?></tt></li>
	<li>Layout file: <tt><?php echo $this->getLayoutFile('main'); ?></tt></li>
</ul>

<p>For more details on how to further develop this application, please read
the <a href="http://www.yiiframework.com/doc/">documentation</a>.
Feel free to ask in the <a href="http://www.yiiframework.com/forum/">forum</a>,
should you have any questions.</p>

protected/views/admin/login.php
<div class="home">
  <h1>Login</h1>

  <p>Please fill out the following form with your login credentials:</p>

  <div class="form">
  <?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'login-form',
    'enableClientValidation'=>true,
    'clientOptions'=>array(
      'validateOnSubmit'=>true,
    ),
  )); ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <div class="row">
      <?php echo $form->labelEx($model,'username'); ?>
      <?php echo $form->textField($model,'username'); ?>
      <?php echo $form->error($model,'username'); ?>
    </div>

    <div class="row">
      <?php echo $form->labelEx($model,'password'); ?>
      <?php echo $form->passwordField($model,'password'); ?>
      <?php echo $form->error($model,'password'); ?>

    </div>

    <div class="row rememberMe">
      <?php echo $form->checkBox($model,'rememberMe'); ?>
      <?php echo $form->label($model,'rememberMe'); ?>
      <?php echo $form->error($model,'rememberMe'); ?>
    </div>

    <div class="row buttons">
      <?php echo CHtml::submitButton('Login'); ?>
    </div>

  <?php $this->endWidget(); ?>
  </div><!-- form -->
</div>

protected/views/admin/newquest.php
<div class="home">
  <div class="register">
    <div class="content bodyText">
      <?php
        $form = $this->beginWidget('CActiveForm', array(
          'id' => 'user-form',
          'enableAjaxValidation' => false,
          'enableClientValidation' => true,
          'clientOptions' => array(
              'validateOnSubmit' => true,
          ),
        ));
      ?>
      <?php echo $form->labelEx($model, 'pertanyaan'); ?><br />
      <?php echo $form->textArea($model, 'text',array('size'=>90)); ?>
      <?php echo $form->error($model, 'text'); ?>
      <br /><br />
      <?php echo $form->labelEx($model, 'insert_choice'); ?><br />
      1.
      <?php echo $form->textField($model, 'multiple_choice[0]', array('required' => true)); ?>
      <br /><br />
      2.
      <?php echo $form->textField($model, 'multiple_choice[1]', array('required' => true)); ?>
      <br /><br />
      3.
      <?php echo $form->textField($model, 'multiple_choice[2]', array('required' => true)); ?>
      <br /><br />
      <?php echo $form->labelEx($model, 'the_aswer_is'); ?><br />
      <?php echo $form->textField($model, 'answer'); ?>
      <br /><br />
      <?php echo $form->labelEx($model, 'hint'); ?><br />
      <?php echo $form->textField($model, 'hint'); ?>
      <br /><br />
      <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
      <?php $this->endWidget(); ?>
    </div>
  </div>
</div>

protected/views/admin/post.php
<div class="home">
  <div class="content bodyText">
    <p><?php echo CHtml::link('new article', array('admin/article')); ?></p>
  	<table>
      <thead>
      	<tr>
      		<th>No.</th>
      		<th>Nama Article</th>
      		<th>Tanggal Edit</th>
          <th>Action</th>
      	</tr>
      </thead>
      <tbody>
    		<?php for ($i = 0; $i < count($data); $i++) { ?>
        	<tr>
        		<td><?php echo ($i + 1); ?></td>
        		<td>
              <?php echo $data[$i]->text; ?>
        		</td>
        		<td>
    			     <?php echo $data[$i]->created_at; ?>
    		    </td>
            <td>
              <?php echo CHtml::link('edit', 'editarticle?id=' . $data[$i]->id, array('admin/editarticle')); ?>
              <?php echo CHtml::link('delete', 'deletearticle?id=' . $data[$i]->id, array('admin/deletearticle')); ?>
            </td>
      		</tr>
    		<?php } ?>
      </tbody>
    </table>
  </div>
</div>

protected/views/admin/questions.php
<div class="home">
  <div class="content bodyText">
    <p><?php echo CHtml::link('new question', array('admin/newquest')); ?></p>
  	<table>
      <thead>
      	<tr>
      		<th>No.</th>
      		<th>Isi pertanyaan</th>
      		<th>Schedule</th>
          <th>Action</th>
      	</tr>
      </thead>
      <tbody>
    		<?php for ($i = 0; $i < count($data); $i++) { ?>
        	<tr>
        		<td><?php echo ($i + 1); ?></td>
        		<td>
              <?php echo $data[$i]->text; ?>
        		</td>
        		<td>
    			     <?php echo $data[$i]->schedule; ?>
    		    </td>
            <td>
              <?php echo CHtml::link('edit', 'editquest?id=' . $data[$i]->id, array('admin/editquest')); ?>
              <?php echo CHtml::link('delete', 'deletequest?id=' . $data[$i]->id, array('admin/deletequest')); ?>
            </td>
      		</tr>
    		<?php } ?>
      </tbody>
    </table>
  </div>
</div>

protected/views/admin/showarticle.php
<div class="home">
  <div class="content bodyText">
  <div class="headText">
    &ndash; KONDISI POHON &ndash;
  </div>
  <br />
  <div class="treeData">
    <?php echo $cond; ?>
  </div>
  <br /><br />
  <div class="headText">
    &ndash; POINT ANDA &ndash;
  </div>
  <br />
  <div class="treeData">
      <?php echo $data->point; ?>
  </div>
  <br /><br />
  <?php echo CHtml::link('
  <div class="link">
      SHARE
  </div>
  ', Yii::app()->request->hostInfo . Yii::app()->request->baseURL . '/' . $data->fb_id . '', array('data-image' => '', 'data-desc' => $data->first_name, 'class' => 'fbShare', 'data' => 'fb')); ?>
  <br />
  <?php echo CHtml::link('
  <div class="link">
      GET POINT
  </div>
  ', array('site/getpoint')); ?>
  </div>
</div>