protected/controllers/AdminController.php
<?php

class AdminController extends Controller
{
  /**
   * Declares class-based actions.
   */
  public function actions()
  {

    return array(
      // captcha action renders the CAPTCHA image displayed on the contact page
      'captcha'=>array(
        'class'=>'CCaptchaAction',
        'backColor'=>0xFFFFFF,
      ),
      // page action renders "static" pages stored under 'protected/views/site/pages'
      // They can be accessed via: index.php?r=site/page&view=FileName
      'page'=>array(
        'class'=>'CViewAction',
      ),
    );
  }

  /**
   * This is the default 'index' action that is invoked
   * when an action is not explicitly requested by users.
   */
  public function actionIndex()
  {
    // renders the view file 'protected/views/site/index.php'
    // using the default layout 'protected/views/layouts/main.php'
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
      $this->redirect(array('admin/post'));
    }
  }

  /**
   * This is the action to handle external exceptions.
   */
  public function actionError()
  {
    if($error=Yii::app()->errorHandler->error)
    {
      if(Yii::app()->request->isAjaxRequest)
        echo $error['message'];
      else
        $this->render('error', $error);
    }
    $this->layout = 'adminmain';
  }

  /**
   * Displays the login page
   */
  public function actionLogin()
  {
    $model=new LoginForm;

    // if it is ajax validation request
    if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
    {
      echo CActiveForm::validate($model);
      Yii::app()->end();
    }

    // collect user input data
    if(isset($_POST['LoginForm']))
    {
      $model->attributes=$_POST['LoginForm'];
      // validate user input and redirect to the previous page if valid
      if($model->validate() && $model->login())
        $this->redirect(array('admin/index'));
    }
    // display the login form
    $this->layout = 'adminmain';
    $this->render('login',array('model'=>$model));
  }

  /**
   * Logs out the current user and redirect to homepage.
   */
  public function actionLogout()
  {
    Yii::app()->user->logout();
    $this->layout = 'adminmain';
    $this->redirect(array('admin/login'));
  }

  public function actionArticle(){

    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
      $model = new Article;

      if (isset($_POST['Article'])) {
        $model->attributes = $_POST['Article'];
        $model->created_at = date('Y-m-d H:i:s');
        if($model->save()){
          $this->redirect(array('admin/post'));
        }else{
          $this->render('article',array('model'=>$model));
        }
        }else{
          $this->render('article',array('model'=>$model));
        }
      }
    }

  public function actionPost()
  {
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
      $data = Article::model()->findAll(array('order' => 'created_at DESC'));
      $this->render('post', array('data' => $data));
    }
  }

  public function actionEditarticle($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Article::model()->findBySql('SELECT * FROM article WHERE id = "' . $id . '"');

    if (isset($_POST['Article'])) {
      $data->attributes = $_POST['Article'];
      $data->created_at = date('Y-m-d H:i:s');
      if($data->save()){
        $this->redirect(array('admin/post'));
      }else{
        $this->render('editarticle', array('data' => $data));
      }
      }else{
        $this->render('editarticle', array('data' => $data));
      }
    }
  }

  public function actionDeletearticle($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Article::model()->findBySql('SELECT * FROM article WHERE id = "' . $id . '"');

      if($data->delete()){
        $this->redirect(array('admin/post'));
      }else{
        $this->redirect(array('admin/post'));
      }
    }
  }

  public function actionShowarticle($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Article::model()->findBySql('SELECT * FROM article WHERE id = "' . $id . '"');

      if($data->delete()){
        $this->redirect(array('admin/detailarticle'));
      }else{
        $this->redirect(array('admin/detailarticle'));
      }
    }
  }

  public function actionQuestions(){
    $this->layout = 'adminmain';
    $data = Question::model()->findAll(array('order' => 'schedule DESC'));
    $this->render('questions', array('data' => $data));
  }

  public function actionNewquest(){
    $this->layout = 'adminmain';
    $model = new Question;
    $choice = array();

    if (isset($_POST['Question'])) {
      $model->attributes = $_POST['Question'];
      for($i=0; $i<count($_POST['Question']['multiple_choice']); $i++){
        $ask = $i+1;
        $sem = $ask>=3 ? "" : ";";
        array_push($choice, $ask."==".$_POST['Question']['multiple_choice'][$i].$sem);
      }
      $model->multiple_choice = implode('',$choice);
      $model->schedule = date('Y-m-d H:i:s');
      if($model->save()){
        $this->redirect(array('admin/questions'));
      }else{
        $this->render('newquest',array('model'=>$model));
      }
    }else{
      $this->render('newquest',array('model'=>$model));
    }
  }

  public function actionEditquest($id){
    $this->layout = 'adminmain';
    $model = Question::model()->findBySql('SELECT * FROM question WHERE id = "' . $id . '"');
    $choice = array();

    if (isset($_POST['Question'])) {
      $model->attributes = $_POST['Question'];
      for($i=0; $i<count($_POST['Question']['multiple_choice']); $i++){
        $ask = $i+1;
        $sem = $ask>=3 ? "" : ";";
        array_push($choice, $ask."==".$_POST['Question']['multiple_choice'][$i].$sem);
      }
      $model->multiple_choice = implode('',$choice);
      $model->schedule = date('Y-m-d H:i:s');
      if($model->save()){
        $this->redirect(array('admin/questions'));
      }else{
        $this->render('editquest',array('model'=>$model));
      }
    }else{
      $this->render('editquest',array('model'=>$model));
    }
  }

  public function actionDeletequest($id){
    $this->layout = 'adminmain';
    if(!(Yii::app()->user->name == 'admin')){
      $this->redirect(array('admin/login'));
    }else{
    $data = Question::model()->findBySql('SELECT * FROM question WHERE id = "' . $id . '"');

      if($data->delete()){
        $this->redirect(array('admin/questions'));
      }else{
        $this->redirect(array('admin/questions'));
      }
    }
  }
}

protected/controllers/SiteController.php
<?php

  class SiteController extends Controller {
    public function actions() {
      return array(
        'captcha' => array(
          'class' => 'CCaptchaAction',
          'backColor' => 0xFFFFFF,
        ),
        'page' => array(
          'class' => 'CViewAction',
        ),
      );
    }

    protected function afterRender($view, &$output) {
      parent::afterRender($view, $output);
      Yii::app()->facebook->initJs($output);
      Yii::app()->facebook->renderOGMetaTags();
      return true;
    }

    /*
     * Login facebook PHP code
     */
    public function actionFblogin() {
      try {
        $params = array(
          'scope' => 'user_likes,read_stream,publish_stream,publish_actions,manage_pages,email,user_checkins',
          'redirect_uri' => Yii::app()->request->hostInfo . Yii::app()->request->baseURL . '/site/tutorial'
        );
        $url = Yii::app()->facebook->getLoginURL($params);
        $this->redirect($url);
      } catch (FacebookApiException $e) {
        echo $e;
      }
    }

    /*
     * Logout facebook PHP code
     */
    public function actionFblogout() {
      Yii::app()->facebook->destroySession();
      $this->redirect(array('site/index'));
    }

    /*
     * detect like facebook page PHP
    */
    private function fbLikes() {
      $user = Yii::app()->facebook->getUser();
      if ($user) {
        try {
          $fan_id = '652517128126836';
          $datas = Yii::app()->facebook->api("me/likes/$fan_id", 'GET');
          $like = $datas['data'];
          $count = count($like);
          return $count;
        } catch (FacebookApiException $e) {
          $this->redirect(array('site/index'));
        }
      } else {
        $e = "Koneksi ke Facebook Terputus";
        return $e;
      }
    }

    /*
     * Share facebook PHP code
    */
    public function actionFbshare() {
      $user = Yii::app()->facebook->getUser();
      try {
        $publishStream = Yii::app()->facebook->api("/$user/feed", 'post', array(
          'message' => 'Check out 25 labs',
          'link' => 'http://25labs.com',
          'picture' => 'http://25labs.com/images/25-labs-160-160.jpg',
          'name' => '25 labs',
          'caption' => '25labs.com',
          'description' => 'A Technology Laboratory. Highly Recomented technology blog.',
        ));
      } catch (FacebookApiException $e) {
        error_log($e);
      }
    }

    public function actionAboutus() {
      $criteria = new CDbCriteria();
      $criteria->order = 'created_at desc';
      $count = Article::model()->count($criteria);
      $pages = new CPagination($count);

      // results per page
      $pages->pageSize=3;
      $pages->applyLimit($criteria);
      $data = Article::model()->findAll($criteria);

      $userdata = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->facebook->getUser() . '"');
      if (count($userdata) != 0) {
        $return = ReturnLink::model()->findBySql('SELECT * FROM return_link WHERE fb_id = "' . $userdata->fb_id . '"');
        if(isset($_POST['User'])){
          $userdata->point = $userdata->point + 20;
          if($userdata->tree_cond >= 2 && $userdata->tree_cond <= 5){ $userdata->tree_cond = $userdata->tree_cond + 1; }
          $userdata->save();
        }
        $this->render('about', array('data' => $data, 'return'=>$return, 'userdata'=>$userdata,'pages' => $pages));
      } else {
        $this->redirect(array('site/index'));
      }
    }

    public function actionRules() {
      $this->render('rules');
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
    */
    public function actionIndex() {
      // renders the view file 'protected/views/site/index.php'
      // using the default layout 'protected/views/layouts/main.php'
      if (isset($_GET['d'])) {
        Yii::app()->session['sharer'] = $_GET['d'];
      }
      if (Yii::app()->facebook->getUser() != 0) {
        $this->redirect(array('site/register', ));
      } else {
        $this->layout = false;
        $this->render('index');
      }
    }

    public function actionRegister() {
      if (Yii::app()->facebook->getUser() != 0) {
        $data = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->facebook->getUser() . '"');
        if (count($data) == 0) {
          $model = new User;

          if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
            $model->fb_id = Yii::app()->facebook->getUser();
            $model->point = 10;
            $model->tree_cond = 5;
            $model->created_time = date('Y-m-d H:i:s');
            if ($model->save()) {
              if (isset(Yii::app()->session['sharer'])) {
                $share = new ReturnLink;
                $_POST['ReturnLink'] = true;
                if (isset($_POST['ReturnLink'])) {
                  $share->attributes = $_POST['ReturnLink'];
                  $share->fb_id = Yii::app()->session['sharer'];
                  $share->clicker = Yii::app()->facebook->getUser();
                  $share->created_time = date('Y-m-d H:i:s');

                  if ($share->save()) {
                    $userShare = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->session['sharer'] . '"');
                    $userShare->point = $userShare->point + 50;
                    if($userShare->tree_cond >= 2 && $userShare->tree_cond <= 5){
                      $userShare->tree_cond = $userShare->tree_cond + 1;
                    }
                    $userShare->save();
                  }
                }
              }
              $this->redirect(array('site/tutorial'));
            }
          }
          $this->render('register', array('model' => $model, 'data'=>$data));
        } else {
          $this->redirect(array('site/tutorial'));
        }
      } else {
        $this->redirect(array('site/index'));
      }
    }

    public function actionHome() {
      $data = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->facebook->getUser() . '"');
      if (count($data) != 0) {
        $datex= date_create($data->created_time);
        $dd = date_add($datex, date_interval_create_from_date_string('3 days'));
        $yy = date_format($dd, 'Y-m-d Y-m-d H:i:s');
        $xx = date("Y-m-d H:i:s");

        if($xx > $yy){
          if($data->tree_cond >=2 && $data->tree_cond <= 5){
            $data->tree_cond = $data->tree_cond - 1;
            $data->created_time = date("Y-m-d H:i:s");
            $data->save();
          }
        }
        $this->render('home', array('data' => $data));
      } else {
        $this->redirect(array('site/index'));
      }
    }

    public function actionLeaderboard() {
      $data = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->facebook->getUser() . '"');
      if (count($data) != 0) {
        $criteria = new CDbCriteria();
        $criteria->order = 'point desc';
        $count = User::model()->count($criteria);
        $pages = new CPagination($count);

        // results per page
        $pages->pageSize = 20;
        $pages->applyLimit($criteria);

        $usersData = User::model()->findAll($criteria);;
        $this->render('leaderboard', array('data' => $data, 'usersData' => $usersData, 'pages' => $pages));
      } else {
        $this->redirect(array('site/index'));
      }
    }

    public function actionGetpoint() {
      $data = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->facebook->getUser() . '"');
      if (count($data) != 0) {
        $return = ReturnLink::model()->findBySql('SELECT * FROM return_link WHERE fb_id = "' . $data->fb_id . '"');

        $question = Question::model()->findAllBySql('SELECT * FROM question WHERE schedule < "' . date('Y-m-d H:i:s') . '"');
        $dataAns = Answer::model()->findAllBySql('SELECT * FROM answer WHERE fb_id = "' . $data->fb_id . '"');

        $model = new Answer;

        if (isset($_POST['Answer'])) {
          $model->attributes = $_POST['Answer'];
          $model->fb_id = $data->fb_id;
          $model->question_id = $question[count($dataAns)]->id;
          $model->created_time = date('Y-m-d H:i:s');
          $userUpdate = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . $data->fb_id . '"');
          if ($question[count($dataAns)]->answer == $model->answer) {
            $userUpdate->point = $userUpdate->point + 20;
            if($userUpdate->tree_cond >= 3 && $userUpdate->tree_cond <= 5){
              $userUpdate->tree_cond = $userUpdate->tree_cond + 1;
            }
            $userUpdate->save();
          }
          if ($model->save()) {
            $this->refresh();
          }
        }
          $this->render('getpoint', array('data' => $data, 'return' => $return, 'question' => $question, 'dataAns' => $dataAns, 'model' => $model));
      } else {
        $this->redirect(array('site/index'));
      }
    }

    public function actionShare() {
      $data = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->facebook->getUser() . '"');
      if (count($data) != 0) {
        if (isset($_POST['p'])) {
          $data_share = DataShare::model()->findBySql('SELECT * FROM data_share WHERE fb_id = "' . Yii::app()->facebook->getUser() . '" AND created_time LIKE "' . date('Y-m-d') . '%" AND via = "' . $_POST['p'] . '"');
          if (count($data_share) == 0) {
            $model = new DataShare;

            $_POST['DataShare'] = true;
            if (isset($_POST['DataShare'])) {
              $model->attributes = $_POST['DataShare'];

protected/views/layouts/adminmain.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="language" content="en" />

  <!-- blueprint CSS framework -->
  <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/css/screen.css" media="screen, projection" />
  <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/css/print.css" media="print" />
  <!--[if lt IE 8]>
  <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
  <![endif]-->

  <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/css/mainadmin.css" />
  <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/css/form.css" />
  <style>
    .home{margin:30px;}
  </style>

  <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

  <div id="header">
    <div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
  </div><!-- header -->

  <div id="mainmenu">
    <?php
      $this->widget('zii.widgets.CMenu',array(
      'items'=>array(
        array('label'=>'Article', 'url'=>array('/admin/post'),'visible'=>!Yii::app()->user->isGuest),
        array('label'=>'Questions', 'url'=>array('/admin/questions'),'visible'=>!Yii::app()->user->isGuest),
        array('label'=>'Login', 'url'=>array('/admin/login'), 'visible'=>Yii::app()->user->isGuest),
        array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/admin/logout'), 'visible'=>!Yii::app()->user->isGuest)
      ),
    )); ?>
  </div><!-- mainmenu -->
  <?php if(isset($this->breadcrumbs)):?>
    <?php $this->widget('zii.widgets.CBreadcrumbs', array(
      'links'=>$this->breadcrumbs,
    )); ?><!-- breadcrumbs -->
  <?php endif?>

  <?php echo $content; ?>

</div><!-- page -->

</body>
</html>

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div class="span-19">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
	<div class="span-5 last">
		<div id="sidebar">
		<?php
			$this->beginWidget('zii.widgets.CPortlet', array(
				'title'=>'Operations',
			));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->menu,
				'htmlOptions'=>array('class'=>'operations'),
			));
			$this->endWidget();
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="icon" type="image/ico" href="<?php echo Yii::app()->request->baseUrl; ?>/library/favicon.ico" />

    <!--[if lt IE 8]>
      <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/library/css/ie.css" media="screen, projection" />
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/library/css/custom-main.css" />
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

    <?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
    <?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/library/js/common.js'); ?>
    <?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/library/js/jquery-1.8.2.js'); ?>
    <?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/library/js/bootstrap.min.js'); ?>
    <?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/library/js/pictree.js'); ?>
    <?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/library/js/about.js'); ?>

    <script type="text/javascript" src="<?php echo Yii::app()->baseUrl.'/library/js/showarticle.js';?>" defer="defer"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->baseUrl.'/library/js/index.js';?>" defer="defer"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->baseUrl.'/library/js/home.js';?>" defer="defer"></script>

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
  </head>
  <body>
    <?php $baseUrl = Yii::app()->request->baseUrl . "/library/images/"; ?>
    <div class="bgCont">
	    <?php echo CHtml::image($baseUrl . 'nutrilite_bg.jpg', 'nutrilite image', array('class' => 'picFXY')); ?>
	    <?php
        $data = User::model()->findBySql('SELECT * FROM user WHERE fb_id = "' . Yii::app()->facebook->getUser() . '"');
        $req = Yii::app()->urlManager->parseUrl(Yii::app()->request);
        if($req=='site/home'){
          if (count($data) == 0) {
            echo CHtml::image($baseUrl . 'nutrilite_tree.png', 'nutrilite image', array('id' => 'picTree'));
          }
        }else{
          echo CHtml::image($baseUrl . 'nutrilite_tree.png', 'nutrilite image', array('id' => 'picTree'));
        }
      ?>
	    <?php echo CHtml::image($baseUrl . 'nutrilite_leaftr.png', 'nutrilite image', array('class' => 'leaf leaft leafr')); ?>
	    <?php echo CHtml::image($baseUrl . 'nutrilite_leaftl.png', 'nutrilite image', array('class' => 'leaf leaft leafl')); ?>
	    <?php echo CHtml::image($baseUrl . 'nutrilite_leafbr.png', 'nutrilite image', array('class' => 'leaf leafb leafr')); ?>
	    <?php echo CHtml::image($baseUrl . 'nutrilite_leafbl.png', 'nutrilite image', array('class' => 'leaf leafb leafl')); ?>
	  </div>
    <?php if (count($data) != 0) { ?>
      <div class="profile-link">
        <ul class="menuCont hf">
          <li><strong><?php echo "Hai ". $data->first_name . " " . $data->last_name;?></strong></li>
          <li><?php echo CHtml::link('EDIT PROFILE', array('site/profile')); ?></li>
        </ul>
      </div>
    <?php } ?>
    <div id="main-page">
      <div class="logobrand"><img class="eightith shake" src="<?php echo $baseUrl.'nutrilite_80th.png'; ?>" alt="nutrilite image"></div>
    	<div class="mainMenuCont">
        <div class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><?php echo CHtml::link('HOME', array('site/home')); ?></li>
                <li><?php echo CHtml::link('LEADERBOARD', array('site/leaderboard'), array("title"=>"Lihat siapa yang meraih poin tertinggi")); ?></li>
                <li><?php echo CHtml::link('GET POINT', array('site/getpoint'), array("title"=>"Tambah terus poin Anda, selesaikan tantangannya setiap hari")); ?></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><?php echo CHtml::link('SYARAT &amp; KETENTUAN', array('site/rules'), array("title"=>"Info lengkap tentang Nutrilite Virtual Tree")); ?></li>
                <li><?php echo CHtml::link('TENTANG NUTRILITE', array('site/aboutus'), array("title"=>"Ingin poin ekstra? Share artikel seputar Nutrilite di sini")); ?></li>
                <li class="logout"><?php echo CHtml::link('LOGOUT', array('site/logout')); ?></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
	  <div class="logoCont"><?php echo CHtml::image($baseUrl . 'nutrilite_logo.png', 'nutrilite image', array('class' => 'piclogo')); ?></div>
    <div id="page"><?php echo $content; ?></div>
  </body>
</html>